# App: Customer Registration
# Package: db
# File: docker-compose.yml
# Version: 0.1.0
# Turns: 2
# Author: Codex Agent
# Date: 2025-09-25T06:25:09Z
# Description: Local PostgreSQL stack for developing the customer registration database.
version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: customer-registration-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_registration
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: {}
