# App: Customer Registration
# Package: db
# File: docker-compose.yml
# Version: 0.1.0
# Turns: 2
# Author: Codex Agent
# Date: 2025-09-20T04:22:15Z
# Exports: (docker compose configuration)
# Description: Docker Compose stack providing a PostgreSQL instance for local
#              development and automated testing workflows.
version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-customer_service}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-customer_service}
      POSTGRES_DB: ${DATABASE_NAME:-customer_service}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USERNAME:-customer_service}']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
